export interface JourneyDayContent {
  day: number;
  title: string;
  dial: 'PLATE' | 'MOVE' | 'LIFT' | 'REST' | 'REPEAT';
  mission: string;
  whyItMatters: string;
  action: string;
  reflectionPrompt: string;
}

export const JOURNEY_DAYS: JourneyDayContent[] = [
  {
    day: 1,
    title: 'The Baseline Observation',
    dial: 'REPEAT',
    mission: 'Observe without judging. Notice your routine as it actually is.',
    whyItMatters: 'Sustainable transformation starts from radical self-honesty, not frantic restriction. We understand the person first before personalizing.',
    action: 'Log your meals and bedtime today exactly as they happen without trying to make them "perfect".',
    reflectionPrompt: 'What was one pattern you noticed today that usually slips by unnoticed?',
  },
  {
    day: 2,
    title: 'The Morning Protein Anchor',
    dial: 'PLATE',
    mission: 'Pair your morning carbohydrate with a non-negotiable protein source.',
    whyItMatters: 'Protein releases peptide YY and GLP-1 while suppressing morning ghrelin spikes, blunting energy crashes at 11 AM.',
    action: 'If eating dosa or idli, add 2 eggs or a bowl of sprouted green gram or boiled kadala.',
    reflectionPrompt: 'How did having protein at breakfast affect your energy and cravings before lunch?',
  },
  {
    day: 3,
    title: 'The 15-Minute Post-Meal Pulse',
    dial: 'MOVE',
    mission: 'Take an unbroken 15-minute gentle walk immediately after your largest meal.',
    whyItMatters: 'Contracting your quadriceps and calves acts as a glucose sink, absorbing circulating sugars directly without demanding excess insulin spikes.',
    action: 'Step away from your desk right after lunch and walk at a comfortable conversational pace for 15 minutes.',
    reflectionPrompt: 'Did you notice any reduction in post-lunch sleepiness or sluggishness?',
  },
  {
    day: 4,
    title: 'The Half-Plate Rule',
    dial: 'PLATE',
    mission: 'Dedicate half of your lunch and dinner plates to colorful vegetables or thoran.',
    whyItMatters: 'Dietary fiber creates mechanical stretch receptors in the stomach wall, signaling satiety to the brain without eliminating rice or chapatis.',
    action: 'Fill half your plate with cabbage thoran, beans, cucumber salad, or spinach before serving your rice and protein.',
    reflectionPrompt: 'How easy was it to eat your traditional favorites while prioritizing vegetable volume first?',
  },
  {
    day: 5,
    title: 'The 15-Minute Craving Protocol',
    dial: 'REPEAT',
    mission: 'When a strong sweet or snack craving strikes, enforce a calm 15-minute delay.',
    whyItMatters: 'Most cravings are dopamine-seeking micro-urges triggered by stress, fatigue, or habit loops that dissolve within 12–15 minutes.',
    action: 'Drink a 300ml glass of water, eat a handful of roasted makhana or curd, and walk to a different room for 15 minutes before deciding.',
    reflectionPrompt: 'Did the intensity of the craving change after you paused and hydrated?',
  },
  {
    day: 6,
    title: 'Structured Hydration Rhythm',
    dial: 'REST',
    mission: 'Distribute 2.5–3.0 liters of water evenly throughout your active daylight hours.',
    whyItMatters: 'Mild dehydration is frequently misinterpreted by the hypothalamus as hunger. Ending heavy water intake 1 hour before bed protects deep sleep.',
    action: 'Drink 1 tall glass upon waking, 1 glass 30 minutes before each main meal, and finish your hydration by 8:30 PM.',
    reflectionPrompt: 'Did you notice fewer evening false-hunger alarms when your hydration was consistent?',
  },
  {
    day: 7,
    title: 'Week 1 Review & Dial Calibration',
    dial: 'REPEAT',
    mission: 'Celebrate 7 days of consistency and identify your single friction point.',
    whyItMatters: 'Progress is built through weekly feedback loops. We do not punish deviations; we adapt the system to fit your real life.',
    action: 'Complete your Week 1 Review in the Insights tab and select your #1 priority dial for next week.',
    reflectionPrompt: 'Which dial felt most effortless this week, and which dial needs a gentler approach?',
  },
  {
    day: 8,
    title: 'Strength Foundation (Stimulate, Don’t Annihilate)',
    dial: 'LIFT',
    mission: 'Perform 3 sets of compound bodyweight or resistance exercises.',
    whyItMatters: 'Resistance exercise signals your body to preserve precious lean muscle tissue during fat loss, keeping your resting metabolic rate robust.',
    action: 'Complete 3 sets of 10 bodyweight squats, 8 counter/wall push-ups, and a 30-second plank.',
    reflectionPrompt: 'How did it feel to prioritize movement quality and muscle engagement over exhaustion?',
  },
  {
    day: 9,
    title: 'Mastering Traditional Rice & Breads',
    dial: 'PLATE',
    mission: 'Enjoy Kerala Matta rice, chapati, or appam without guilt or fear.',
    whyItMatters: 'Carbohydrates are not the enemy. The Blueprint teaches portion awareness, pairing carbs with fiber and protein to control glycemic speed.',
    action: 'Measure 1 standard cup of cooked rice. Eat your protein and thoran first, then savor the rice mindfully.',
    reflectionPrompt: 'Did enjoying your cultural food mindfully free you from the all-or-nothing diet trap?',
  },
  {
    day: 10,
    title: 'The Digital Curfew',
    dial: 'REST',
    mission: 'Dim overhead lights and set phones to grayscale 45 minutes before sleep.',
    whyItMatters: 'High-energy blue light suppresses melatonin synthesis, degrading REM and slow-wave restorative sleep.',
    action: 'Charge your phone across the room tonight. Read a physical book or listen to calming audio before sleep.',
    reflectionPrompt: 'How did you sleep when your eyes were spared from late-night screens?',
  },
  {
    day: 11,
    title: 'The Restaurant & Social Dining Strategy',
    dial: 'PLATE',
    mission: 'Navigate dining out with confidence using the pre-dining protein bridge.',
    whyItMatters: 'Social occasions should be enjoyed. Arriving ravenous leads to compulsive overeating of high-fat fried appetizers.',
    action: 'Have 2 boiled eggs or a cup of spiced buttermilk before leaving home, and order a salad or grilled protein first at the restaurant.',
    reflectionPrompt: 'Did having a pre-dining anchor make social dining more relaxed and conscious?',
  },
  {
    day: 12,
    title: 'The Liquid Calorie Audit',
    dial: 'PLATE',
    mission: 'Audit sweetened teas, coffees, juices, and soft drinks.',
    whyItMatters: 'Liquid sugars produce minimal satiety response in the gut while delivering rapid caloric surges to the liver.',
    action: 'Swap sweetened chai or soda for black cardamom tea, infused lime water, or plain sparkling water today.',
    reflectionPrompt: 'Were you able to find satisfaction in refreshing unsweetened beverages?',
  },
  {
    day: 13,
    title: 'The 20-Minute Meal Pace',
    dial: 'REPEAT',
    mission: 'Slow down your eating pace so meals take at least 20 minutes.',
    whyItMatters: 'Satiety hormones (cholecystokinin and leptin) require approximately 15–20 minutes to signal the hypothalamus that you are nourished.',
    action: 'Put down your spoon or fork between bites and chew thoroughly until food is liquified.',
    reflectionPrompt: 'Did eating slower help you recognize comfortable fullness before feeling overstuffed?',
  },
  {
    day: 14,
    title: 'Two-Week Milestone & Non-Scale Victories',
    dial: 'REPEAT',
    mission: 'Look beyond the scale to energy, clothing fit, mood, and skin clarity.',
    whyItMatters: 'Body composition improves before bathroom scale fluctuations reflect water weight drops.',
    action: 'Note three non-scale victories you have experienced over the past 14 days in your journal.',
    reflectionPrompt: 'What positive change in your daily life makes you proudest right now?',
  },
  {
    day: 15,
    title: 'Progressive Overload at Home',
    dial: 'LIFT',
    mission: 'Add 2 repetitions or 5 seconds of pause to each exercise.',
    whyItMatters: 'Muscles adapt to demands. Increasing tension slightly signals continued muscle preservation.',
    action: 'Add a 2-second pause at the bottom of each bodyweight squat and pushup today.',
    reflectionPrompt: 'How did the added muscle tension feel during your workout?',
  },
  {
    day: 16,
    title: 'The Skin Barrier Shield',
    dial: 'REST',
    mission: 'Protect your skin barrier with daily broad-spectrum sunscreen and gentle hydration.',
    whyItMatters: 'UV radiation and pollution trigger inflammatory cascades that compromise collagen and exacerbate post-inflammatory hyperpigmentation.',
    action: 'Apply two finger lengths of SPF 50 sunscreen 15 minutes before stepping outside today.',
    reflectionPrompt: 'How does prioritizing daily skin health connect with your overall self-care rhythm?',
  },
  {
    day: 17,
    title: 'Managing High-Stress Days',
    dial: 'REST',
    mission: 'Use 4-7-8 breathing when stress threatens to trigger emotional eating.',
    whyItMatters: 'Elevated cortisol increases preference for hyper-palatable high-sugar foods by altering hypothalamic sensitivity.',
    action: 'Inhale for 4 seconds, hold for 7 seconds, and exhale slowly through your mouth for 8 seconds. Repeat 4 cycles.',
    reflectionPrompt: 'Did down-regulating your nervous system reduce urgency around impulsive snacking?',
  },
  {
    day: 18,
    title: 'The Weekend Anchor Habit',
    dial: 'REPEAT',
    mission: 'Maintain your wake-up time within 60 minutes of your weekday schedule.',
    whyItMatters: 'Social jetlag disrupts metabolic rhythms and makes Monday mornings feel exhausting.',
    action: 'Wake up at your regular time, hydrate, and take a gentle morning sunlight walk.',
    reflectionPrompt: 'Did keeping weekend sleep consistent help you avoid Monday morning grogginess?',
  },
  {
    day: 19,
    title: 'Pantry & Grocery Mastery',
    dial: 'PLATE',
    mission: 'Stock your kitchen with quick high-protein staples so healthy choices are the default.',
    whyItMatters: 'Convenience drives food choices. When high-protein foods are ready in under 3 minutes, takeout temptation plunges.',
    action: 'Ensure your pantry has eggs, roasted makhana, canned or boiled lentils, curd, and frozen vegetables.',
    reflectionPrompt: 'How does having healthy staples accessible change your weeknight cooking stress?',
  },
  {
    day: 20,
    title: 'The Non-Exercise Activity (NEAT) Boost',
    dial: 'MOVE',
    mission: 'Turn mundane daily moments into incidental movement opportunities.',
    whyItMatters: 'NEAT (Non-Exercise Activity Thermogenesis) burns up to 3x more total daily energy than a 45-minute gym session.',
    action: 'Take calls while pacing, choose stairs over elevators, and park 200 meters further away.',
    reflectionPrompt: 'How many extra steps did you accumulate without needing formal workout gear?',
  },
  {
    day: 21,
    title: 'Week 3 Review: The Habit Loop Lock-In',
    dial: 'REPEAT',
    mission: 'Audit your habit cues, routines, and rewards across all Five Dials.',
    whyItMatters: 'Habits become automatic when the friction between intention and action approaches zero.',
    action: 'Reflect on which habit now feels like second nature compared to Day 1.',
    reflectionPrompt: 'What behavior that felt like an effort on Day 1 now happens automatically?',
  },
  {
    day: 22,
    title: 'Handling Plateau Anxiety',
    dial: 'REPEAT',
    mission: 'Understand that weight plateaus are normal physiological water shifts, not failure.',
    whyItMatters: 'Fat cells frequently fill with water temporarily before collapsing. Consistent habits will break the plateau naturally.',
    action: 'Focus entirely on adhering to your Five Dials today without checking the scale.',
    reflectionPrompt: 'Can you detach your emotional wellbeing from daily scale fluctuations?',
  },
  {
    day: 23,
    title: 'Pre-Bed Magnesium & Wind-Down Ritual',
    dial: 'REST',
    mission: 'Create a calming nighttime environment with warm herbal tea or a warm shower.',
    whyItMatters: 'A warm shower dilates peripheral blood vessels, causing core body temperature to drop, which naturally induces sleepiness.',
    action: 'Take a warm 5-minute shower 45 minutes before bed and sip chamomile or warm water with lemon.',
    reflectionPrompt: 'Did the temperature drop help you drift off to sleep faster?',
  },
  {
    day: 24,
    title: 'Spicing Meals for Satiety and Gut Health',
    dial: 'PLATE',
    mission: 'Use traditional digestive spices like turmeric, black pepper, ginger, and cumin.',
    whyItMatters: 'Spices enhance sensory satisfaction, stimulate digestive enzymes, and provide polyphenol antioxidants for gut bacteria.',
    action: 'Incorporate freshly crushed black pepper and grated ginger into your dal or vegetable preparation.',
    reflectionPrompt: 'How did the rich aromatic seasoning elevate your meal satisfaction?',
  },
  {
    day: 25,
    title: 'Upper Body & Posture Alignment',
    dial: 'LIFT',
    mission: 'Counteract desk-job slouching with chest openers, face pulls, and glute bridges.',
    whyItMatters: 'Desk work creates anterior tightness and posterior weakness. Structural balance eliminates lower back fatigue.',
    action: 'Do 3 sets of 12 glute bridges and 15 doorway chest stretches between work meetings.',
    reflectionPrompt: 'Did stretching and engaging your posterior chain relieve mid-back tension?',
  },
  {
    day: 26,
    title: 'Overcoming the "All-or-Nothing" Mindset',
    dial: 'REPEAT',
    mission: 'Practice the rule: Never miss twice. If one meal is off-plan, reset on the very next decision.',
    whyItMatters: 'One off-track meal never causes weight gain; the belief that "the day is ruined" and subsequent overeating does.',
    action: 'If anything goes off-schedule today, shrug your shoulders and return immediately to your balanced routine.',
    reflectionPrompt: 'How empowering does it feel to know that no single meal has the power to derail you?',
  },
  {
    day: 27,
    title: 'Skin Hydration from Inside Out',
    dial: 'REST',
    mission: 'Assess your barrier hydration, essential fatty acids, and water balance.',
    whyItMatters: 'Omega-3 fatty acids and adequate intracellular hydration maintain lipid bilayer fluidity in skin keratinocytes.',
    action: 'Include omega-rich flaxseed or walnuts, along with your planned hydration today.',
    reflectionPrompt: 'Does your skin feel calmer and more balanced when whole-body hydration is steady?',
  },
  {
    day: 28,
    title: 'The Sustainable Social Protocol',
    dial: 'PLATE',
    mission: 'Enjoy festive or family gatherings while keeping the Plate dial anchored.',
    whyItMatters: 'Lifelong health must coexist with family celebrations, biriyanis, and weddings.',
    action: 'Fill half your plate with salad, raita, and grilled meats first; savor desserts mindfully in small portions.',
    reflectionPrompt: 'How did it feel to celebrate with family without feeling deprived or out of control?',
  },
  {
    day: 29,
    title: 'Designing Your Personal Maintenance System',
    dial: 'REPEAT',
    mission: 'Define your non-negotiables for the next 6 months.',
    whyItMatters: 'The 20 KG Blueprint is not a 30-day crash diet; it is your lifelong operating system.',
    action: 'Choose the two habits that gave you 80% of your results and write them down as lifelong anchors.',
    reflectionPrompt: 'Which habits will you maintain effortlessly for the rest of this year?',
  },
  {
    day: 30,
    title: 'The 30-Day Graduation & Forever Blueprint',
    dial: 'REPEAT',
    mission: 'Reflect on your 30-day evolution from where you started to who you are today.',
    whyItMatters: 'You did not just manage weight; you built identity, confidence, and metabolic resilience.',
    action: 'Review your 30-day progress graphs, celebrate your streak, and unlock the ongoing Maintenance Mode.',
    reflectionPrompt: 'How has your relationship with food, movement, and your body shifted over these 30 days?',
  },
];
