import { NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { clearSessionCookie, getCurrentUser } from '@/lib/auth/session';

export async function GET(req: Request) {
  try {
    const user = await getCurrentUser();
    if (!user) {
      return NextResponse.json({ error: 'Authentication required' }, { status: 401 });
    }

    const { searchParams } = new URL(req.url);
    const action = searchParams.get('action');

    // 1. Export Data in JSON
    if (action === 'export') {
      const profile = db.prepare('SELECT * FROM profiles WHERE user_id = ?').get(user.id);
      const bodyProfile = db.prepare('SELECT * FROM body_profiles WHERE user_id = ?').get(user.id);
      const goals = db.prepare('SELECT * FROM goals WHERE user_id = ?').get(user.id);
      const healthScreen = db.prepare('SELECT * FROM health_screens WHERE user_id = ?').get(user.id);
      const allergyProfile = db.prepare('SELECT * FROM allergy_profiles WHERE user_id = ?').get(user.id);
      const foodProfile = db.prepare('SELECT * FROM food_profiles WHERE user_id = ?').get(user.id);
      const lifestyle = db.prepare('SELECT * FROM lifestyle_profiles WHERE user_id = ?').get(user.id);
      const skin = db.prepare('SELECT * FROM skin_profiles WHERE user_id = ?').get(user.id);
      const dials = db.prepare('SELECT * FROM five_dials WHERE user_id = ?').get(user.id);
      const checkins = db.prepare('SELECT * FROM daily_checkins WHERE user_id = ? ORDER BY date DESC').all(user.id);
      const meals = db.prepare('SELECT * FROM meal_logs WHERE user_id = ? ORDER BY date DESC').all(user.id);
      const journey = db.prepare('SELECT * FROM journey_progress WHERE user_id = ?').get(user.id);
      const skinLogs = db.prepare('SELECT * FROM skin_logs WHERE user_id = ? ORDER BY date DESC').all(user.id);
      const groceries = db.prepare('SELECT * FROM smart_groceries WHERE user_id = ?').all(user.id);
      const consents = db.prepare('SELECT * FROM consents WHERE user_id = ?').get(user.id);

      db.prepare(`
        INSERT INTO audit_logs (id, user_id, action, details)
        VALUES (?, ?, ?, ?)
      `).run(`aud_${Date.now()}`, user.id, 'DATA_EXPORTED', 'Full structured JSON data export generated by user');

      return NextResponse.json({
        exportDate: new Date().toISOString(),
        shiftVersion: '1.0.0-blueprint',
        dataOwner: { id: user.id, email: user.email },
        healthProfile: { profile, bodyProfile, goals, healthScreen, allergyProfile, foodProfile, lifestyle, skin },
        dials,
        trackingHistory: { checkins, meals, skinLogs, journey, groceries },
        privacyAndConsents: consents,
        privacyStatement: 'This personal health data belongs exclusively to you. It is never sold, shared, or used for advertising.',
      });
    }

    // 2. Return current consents & data inventory
    const consents = db.prepare('SELECT * FROM consents WHERE user_id = ?').get(user.id) as any;
    const checkinCount = db.prepare('SELECT count(*) as count FROM daily_checkins WHERE user_id = ?').get(user.id) as any;
    const mealCount = db.prepare('SELECT count(*) as count FROM meal_logs WHERE user_id = ?').get(user.id) as any;
    const skinLogCount = db.prepare('SELECT count(*) as count FROM skin_logs WHERE user_id = ?').get(user.id) as any;

    return NextResponse.json({
      consents: consents || { health_profile_consent: 1, recommendations_consent: 1, analytics_consent: 0 },
      dataInventory: {
        dailyCheckins: checkinCount?.count || 0,
        loggedMeals: mealCount?.count || 0,
        skinLogs: skinLogCount?.count || 0,
      },
    });
  } catch (error) {
    console.error('Privacy GET error:', error);
    return NextResponse.json({ error: 'Privacy operation failed' }, { status: 500 });
  }
}

export async function POST(req: Request) {
  try {
    const user = await getCurrentUser();
    if (!user) {
      return NextResponse.json({ error: 'Authentication required' }, { status: 401 });
    }

    const { action, consents, logType, logId } = await req.json();

    // Update consent settings
    if (action === 'update_consents') {
      db.prepare(`
        INSERT OR REPLACE INTO consents (user_id, health_profile_consent, recommendations_consent, analytics_consent, updated_at)
        VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP)
      `).run(
        user.id,
        consents.healthProfile ? 1 : 0,
        consents.recommendations ? 1 : 0,
        consents.analytics ? 1 : 0
      );

      db.prepare('INSERT INTO audit_logs (id, user_id, action, details) VALUES (?, ?, ?, ?)').run(
        `aud_${Date.now()}`,
        user.id,
        'CONSENTS_UPDATED',
        JSON.stringify(consents)
      );

      return NextResponse.json({ success: true });
    }

    // Delete individual log entry
    if (action === 'delete_entry') {
      if (logType === 'checkin') {
        db.prepare('DELETE FROM daily_checkins WHERE id = ? AND user_id = ?').run(logId, user.id);
      } else if (logType === 'meal') {
        db.prepare('DELETE FROM meal_logs WHERE id = ? AND user_id = ?').run(logId, user.id);
      } else if (logType === 'skin') {
        db.prepare('DELETE FROM skin_logs WHERE id = ? AND user_id = ?').run(logId, user.id);
      }
      return NextResponse.json({ success: true });
    }

    // Delete entire account and all cascading data
    if (action === 'delete_account') {
      db.prepare('DELETE FROM users WHERE id = ?').run(user.id);
      await clearSessionCookie();

      db.prepare('INSERT INTO audit_logs (id, user_id, action, details) VALUES (?, ?, ?, ?)').run(
        `aud_${Date.now()}`,
        'SYSTEM',
        'ACCOUNT_DELETED',
        `User ${user.id} permanently deleted their account and health records.`
      );

      return NextResponse.json({ success: true, message: 'Account and all associated health data permanently erased.' });
    }

    return NextResponse.json({ error: 'Invalid action' }, { status: 400 });
  } catch (error) {
    console.error('Privacy POST error:', error);
    return NextResponse.json({ error: 'Privacy operation failed' }, { status: 500 });
  }
}
